# Generated by Django 5.1.2 on 2025-04-01 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_product_created_at_remove_product_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image_url",
            new_name="image",
        ),
    ]
